### PR TITLE
update Pilmoji.text function to add support of align and anchor

### PR DESCRIPTION
**Pull request by madifaya**
Hello ! 

I propose a solution to implement the parameters "anchor" and "align" into `Pilmoji`.`text`.

this should be linked to Issues : 

- https://github.com/jay3332/pilmoji/issues/14
- https://github.com/jay3332/pilmoji/issues/23

### CODE REVIEW

**Comment by zsilverzweig** [comment]
👍

**Comment by madifaya** [comment]
@jay3332

**Comment by LevaniVashadze** [comment]
@jay3332 could this be merged?

**Comment by madifaya** [comment]
maybe @vertyco, @owocado , @annihilatorrrr or @WitherredAway  can merge too ?

**Comment by WitherredAway** [comment]
> maybe @vertyco, @owocado , @annihilatorrrr or @WitherredAway can merge too ?

I'm not a maintainer

**Comment by annihilatorrrr** [comment]
> maybe @vertyco, @owocado , @annihilatorrrr or @WitherredAway can merge too ?

I'm not a maintainer.

**Comment by LevaniVashadze** [comment]
```pip install git+https://github.com/madifaya/pilmoji.git@add-support-text-align```
Until then this works, but merging would be really useful

**Comment by LevaniVashadze** [comment]
@madifaya Hey I noticed that this change is breaking the spacing between lines when changing it and also it messes up the emojis position when not changing the spacing, for example if the multiline text is: Hello\ntest😉 it breaks the emojis position only if the line doesn't contain a full height character.

**Comment by madifaya** [comment]
> @madifaya Hey I noticed that this change is breaking the spacing between lines when changing it and also it messes up the emojis position when not changing the spacing, for example if the multiline text is: Hello\ntest😉 it breaks the emojis position only if the line doesn't contain a full height character.

I didn't understand what breaks sorry. could you send a picture of the break and/or maybe the implementation that breaks please?

**Comment by LevaniVashadze** [comment]
> > @madifaya Hey I noticed that this change is breaking the spacing between lines when changing it and also it messes up the emojis position when not changing the spacing, for example if the multiline text is: Hello\ntest😉 it breaks the emojis position only if the line doesn't contain a full height character.
> 
> I didn't understand what breaks sorry. could you send a picture of the break and/or maybe the implementation that breaks please? 

Hey the emojis are misaligned, i tried it with apple emojis and they were misaligned in your version(they were too low)

**Pull request merged**
