### PR TITLE
fix for emoji==2.0.0

### LINKED ISSUE #12: There is a problem about import Pilmoji
from pilmoji import Pilmoji
  File "/usr/local/lib/python3.8/dist-packages/pilmoji/__init__.py", line 1, in <module>
    from . import helpers, source
  File "/usr/local/lib/python3.8/dist-packages/pilmoji/helpers.py", line 7, in <module>
    from emoji import EMOJI_UNICODE
ImportError: cannot import name 'EMOJI_UNICODE' from 'emoji' (/usr/local/lib/python3.8/dist-packages/emoji/__init__.py)

My system is Ubuntu 20.04 ,pilmoji version: 2.0.1
What can I do?

### PR DESCRIPTION
**Pull request by owocado**
Hi,

this PR adds fix needed for emoji lib (==2.0.0) as we discussed in DM.

Also resolves #12

### CODE REVIEW

**Comment by jay3332** [comment]
would also appreciate if you changed the requirement in requirements.txt to `emoji>=2` so that it doesn't have to be done in two commits

**Review by jay3332 — CHANGES_REQUESTED** [review]
-

**Comment by jay3332** [comment]
sorry for that, it appears it works fine for emoji<2, so the requirement isn't actually needed. Sorry for the hassle

**Comment by owocado** [comment]
oh sorry. I reverted the commit relating to requirements.txt changes! 👍🏼

**Review by jay3332 — CHANGES_REQUESTED** [review]
One last thing, it would be appreciated if you could bump the version of Pilmoji (__init__.py -> __version__) to 2.0.2, thank you

**Pull request merged**
